# Use python:3.6 as a base image
FROM python:3.6

# Install pandas and xlrd

RUN pip install pandas  && \
    pip install matplotlib  && \
    pip install xlrd && \
    pip install Pillow

RUN useradd -ms /bin/bash  pyuser

USER pyuser

CMD ["python3"]
